### ISSUE TITLE
Buster packages

### ISSUE THREAD

**Issue by bobrik** [saltstack/salt-pack-py3#116]
Debian Buster is coming out soon and it would be nice to have Python 3 packages available.

I've tried installing a Stretch version in a Buster container, but it didn't work, because of tornado version incompatibility. Salt wants < 5, Buster provides 5+.

Current dependencies for Salt provided by Debian:

```
python3-tornado4 (>= 4.2) | python3-tornado (<< 5), python3-tornado4 (>= 4.2) | python3-tornado (>= 4.2)
```

Current dependencies for Salt provided by Saltstack:

```
python3-tornado (>= 4.2.1), python3-tornado (<< 5)
```

Backporting just this should enable Stretch packages on Buster.

**Comment by dmurphy18** [comment]
@bobrik Work is actively occurring to allow for python3-tornado > 5.0 and Salt, as been for some months.  It is also needed for Fedora and EPEL 7 is soon moving to Python 3.6.  Buster will be looked at soon once the next point release for the 2019.2 branch is completed, which is soon.

**Comment by tech-ch1** [comment]
Note that buster provides python3-tornado4 package which is really tornado 4.5.3 (with tornado module renamed as tornado4).

**Comment by Nothing4You** [comment]
Are there any news on this?

**Comment by tj90241** [comment]
Just as a friendly reminder that buster[ is expected to go live in early July](https://wiki.debian.org/ReleasePartyBuster).  Until a Salt repo for Debian buster exists, us Debian stable users will be relegated to Debian 9 or Debian's distro-packaged versions of Salt!

**Comment by jandd** [comment]
[Debian Buster has been released yesterday](https://lists.debian.org/debian-release/2019/07/msg00053.html)

**Comment by dmurphy18** [comment]
IT is planned to have Buster support in the next point release, Salt 2019.2.1 which is currently in QA, no date for release can currently be given. See https://github.com/saltstack/salt/issues/52590.

Closing since a duplicate
