### ISSUE TITLE
Update Standards-Version, sh-systemd etc. for Debian / Ubuntu in Salt spec debian control file

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack-py3#121]
The dh-systemd and Standards-Version are pretty ancient and linter is complaining about it.
Also should check quilt version supported.

**Comment by bryceml** [comment]
Part of https://github.com/saltstack/salt/issues/59588

**Comment by bryceml** [comment]
I updated debian 10 and ubuntu 20.04, so we should at least be good going forward.  It doesn't cause any serious issues in older releases so I think we can call this done.

I'll make sure to update this again when we introduce debian 11 and ubuntu 22.04 as well.
