### ISSUE TITLE
Create pure Python 3 builds for Python 3 Salt

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack-py3#123]
Need to update Python 3 build environment to utilize Python3 salt-minions for nightly builds, and only Python 3 spec and control files.  That is, remove any reliance on Python 2 for building Python 3, since Python 2 will be EOL'd by 2020-01-01.

With support for Python 3 Amazon Linux 2, and RHEL 7 moving from Py 3.4 to Py 3.6, now is the time to accomplish this task.

The upcoming distributions for RHEL 8 and Debian 10  (Buster) are Python 3 defaults, hence would be good to not rely on Python 2.

[x] Redhat 8
[x] Redhat 7
[x] Amazon Linux 2
[] Debian 9
[] Ubuntu 18.04
[] Ubuntu 16.04

Remember in Salt requirements/static/*.in files to update Neon and 2019.2.1 releases for rhel-8.in and debian-10.in

**Comment by Poil** [comment]
Use SCL Python 36 https://www.softwarecollections.org/en/scls/rhscl/rh-python36/ ?

**Comment by dmurphy18** [comment]
@Poil Was thinking about flatpack in some fashion, thanks for the information.

**Comment by bryceml** [comment]
@dmurphy18 can this be closed? I'm not aware of anything that needs done here.

**Comment by dmurphy18** [comment]
yeah closing this left-over reminder.
