### ISSUE TITLE
Create Python 3 M2Crypto package for Debian and Ubuntu 

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-pack-py3#150]
Debian / Ubuntu only provide a Python 2 version of M2Crypto (v0.31.0) and have in their buglist to build a Python 3 version, but it will not be in time for point release Salt 2019.2.1.

See https://github.com/saltstack/salt/issues/54135 which brought this to the attention of SaltStack

**Comment by dmurphy18** [comment]
There is already a Debian python3-m2crypto under development https://packages.debian.org/bullseye/python3-m2crypto

It is available in bullseye and sid, python3-m2crytpo v0.31.0-6.

**Comment by mwidera** [comment]
That's a great news! Thanks for sharing :+1:

**Comment by dawidmalina** [comment]
@dmurphy18 package is also available for 19.04 release https://packages.ubuntu.com/eoan/python3-m2crypto

But I don't think that package will be available for older releases. Would be good if we can have this package for 18.04 LTS.

**Comment by dmurphy18** [comment]
Merged into develop https://github.com/saltstack/salt-pack-py3/pull/151

**Comment by dawidmalina** [comment]
@dmurphy18 as 2019.2.1 is not stable and 2019.2.2 is not ready yet would it be possible to upload this files to 2019.2.0 repo?

**Comment by dawidmalina** [comment]
@dmurphy18 is it possible that m2crypto package will be added also to Ubuntu 16.04? For some reasons it was not added for 2019.2.1 release. https://repo.saltstack.com/py3/ubuntu/16.04/amd64/archive/2019.2.1/
