### ISSUE TITLE
dependency rpms being rebuilt for the same versions

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt-pack-py3#245]
From discussions with @bryceml, I understand that our RPM release process can regenerate dependency rpm packages for versions that already exist in the repository.  A downstream user reports that this can cause problems with repository managers like Artifactory, leading to issues like:

```log
Error:
[Errno -1]Package does not match intended download. Suggestion: run yum --enablerepo=saltstack_repo clean metadata
```

I also understand we may have resolved a similar issue for Debian packages, perhaps we can do the same for rpms.

**Comment by bryceml** [comment]
For the last release, I made sure that the hashes of packages with the same versions were kept in sync with the last release with rsync.  It's a pain to have to do that manually, but I suppose I can do that until we get soe proper automation in place.

**Comment by bryceml** [comment]
This should be fixed now in the automation, leaving this open until I can verify that it works with release candidates, 3003 and a .x release.

**Comment by bryceml** [comment]
Seems to work fine now.
